apiVersion: v1
kind: Service
metadata:
  name: app-01-service
spec:
  selector:
    app: app-01
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: app-02-service
spec:
  selector:
    app: app-02
  type: LoadBalancer
  ports:
    - port: 8091
      targetPort: 8091
