apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
  - port: 80      # Puerto expuesto por el Load Balancer
    targetPort: 3000 # Puerto en el que escucha la aplicación
  selector:
    app: my-app
