spring.application.name=service-config
server.port=9080
debug=true
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.uri=https://github.com/joselizagaravito/ConfigServerProyectoFinal
spring.cloud.config.server.git.username=joselizagaravito
spring.cloud.config.server.git.password=
